name: car_workshop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^11.1.0
  geocoding: ^3.0.0
  http: ^1.2.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
